clone_depth: 1
configuration: Release
image: Visual Studio 2026
platform: x64

environment:
  OSGEO4W_ROOT: C:\OSGeo4W
  PGPASSWORD: Password12!
  UGIS_ARCHIVE: ugis.windows.x64.zip
  UGIS_ROOT: C:\ugis
  WX_ROOT: C:\wxWidgets
  WX_VERSION: 3.3.3

install:
  - mkdir %OSGEO4W_ROOT%
  - ps: Invoke-WebRequest -Uri http://download.osgeo.org/osgeo4w/v2/osgeo4w-setup.exe -OutFile $env:OSGEO4W_ROOT\osgeo4w-setup.exe
  - call %OSGEO4W_ROOT%\osgeo4w-setup.exe -q -k -r -A -s http://download.osgeo.org/osgeo4w/v2 -P curl-devel,gdal-devel,gdal-mss,libjpeg-devel,libmysql-devel,libpng-devel,libpq-devel,libspatialite-devel,sqlite3-devel,zlib-devel -R %OSGEO4W_ROOT% > nul
  - SET INCLUDE=%APPVEYOR_BUILD_FOLDER%\include;C:\Libraries\boost_1_91_0;%OSGEO4W_ROOT%\include;%INCLUDE%
  - SET LIB=%OSGEO4W_ROOT%\lib;%LIB%
  - call %OSGEO4W_ROOT%\bin\o4w_env.bat
  - call C:\Qt\6.11\msvc2022_64\bin\qtenv2.bat
  - call "C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvars64.bat"
  - curl -L -O -S -s https://github.com/wxWidgets/wxWidgets/releases/download/v%WX_VERSION%/wxWidgets-%WX_VERSION%-headers.7z
  - curl -L -O -S -s https://github.com/wxWidgets/wxWidgets/releases/download/v%WX_VERSION%/wxMSW-%WX_VERSION%_vc14x_x64_Dev.7z
  - curl -L -O -S -s https://github.com/wxWidgets/wxWidgets/releases/download/v%WX_VERSION%/wxMSW-%WX_VERSION%_vc14x_x64_ReleaseDLL.7z
  - call "C:\Program Files\7-Zip\7z.exe" x wxWidgets-%WX_VERSION%-headers.7z -o%WX_ROOT% -y > nul
  - call "C:\Program Files\7-Zip\7z.exe" x wxMSW-%WX_VERSION%_vc14x_x64_Dev.7z -o%WX_ROOT% -xr!*.pdb -y > nul
  - call "C:\Program Files\7-Zip\7z.exe" x wxMSW-%WX_VERSION%_vc14x_x64_ReleaseDLL.7z -o%WX_ROOT% -y > nul
  - SET WXWIN=%WX_ROOT%
  - SET PATH=%WX_ROOT%\lib\vc14x_x64_dll;%PATH%
  - cd /d %APPVEYOR_BUILD_FOLDER%
  - net start MSSQL$SQL2022
  - ps: Start-Service MySQL80
  - curl -L -S -s -o %APPVEYOR_BUILD_FOLDER%\postgis-bundle-pg18-3.6.1x64.zip http://download.osgeo.org/postgis/windows/pg18/archive/postgis-bundle-pg18-3.6.1x64.zip
  - call "C:\Program Files\7-Zip\7z.exe" x %APPVEYOR_BUILD_FOLDER%\postgis-bundle-pg18-3.6.1x64.zip -o%APPVEYOR_BUILD_FOLDER% -y > nul
  - xcopy /s /y /q %APPVEYOR_BUILD_FOLDER%\postgis-bundle-pg18-3.6.1x64 "C:\Program Files\PostgreSQL\18"
  - net start postgresql-x64-18
  - call "C:\Program Files\PostgreSQL\18\bin\psql" -U postgres -c "CREATE EXTENSION postgis;"

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\example\ugis
  - qmake
  - nmake

after_build:
  - mkdir %UGIS_ROOT%
  - copy %APPVEYOR_BUILD_FOLDER%\example\ugis\release\ugis.exe %UGIS_ROOT%
  - windeployqt --release --no-translations --no-system-d3d-compiler --no-system-dxc-compiler --no-opengl-sw %UGIS_ROOT%\ugis.exe
  - copy %OSGEO4W_ROOT%\bin\*.dll %UGIS_ROOT%
  - if exist %UGIS_ROOT%\mod_spatialite.dll del /q %UGIS_ROOT%\mod_spatialite.dll
  - call "C:\Program Files\7-Zip\7z.exe" a %APPVEYOR_BUILD_FOLDER%\%UGIS_ARCHIVE% %UGIS_ROOT%\*

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\test
  - SET CXXFLAGS=/DBOAT_TEST_PASSWORD=%PGPASSWORD% /DBOAT_TEST_MSSQL_HOST=(local)\\SQL2022 /DBOAT_TEST_MYSQL_HOST=localhost /DBOAT_TEST_POSTGRES_HOST=localhost&& nmake -f .\windows.makefile test
  - cd %APPVEYOR_BUILD_FOLDER%\test\gui\qt
  - qmake "DEFINES+='BOAT_TEST_PASSWORD=%PGPASSWORD%' 'BOAT_TEST_MSSQL_HOST=(local)\\\\SQL2022' 'BOAT_TEST_MYSQL_HOST=localhost' 'BOAT_TEST_POSTGRES_HOST=localhost'"
  - nmake test
  - cd %APPVEYOR_BUILD_FOLDER%\test\gui\wx
  - SET CXXFLAGS=/DBOAT_TEST_PASSWORD=%PGPASSWORD% /DBOAT_TEST_MSSQL_HOST=(local)\\SQL2022 /DBOAT_TEST_MYSQL_HOST=localhost /DBOAT_TEST_POSTGRES_HOST=localhost&& nmake -f .\windows.makefile test

artifacts:
  - path: $(UGIS_ARCHIVE)
    name: $(UGIS_ARCHIVE)

deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: ugis $(APPVEYOR_REPO_TAG_NAME)
  description: Windows x64 build of ugis
  auth_token:
    secure: +Gn7GWLP1bJNiaRC7DajkAH1q5pkZHgj01H3eX6ZxP5zCoF9Ew+wunr5r9EmHdz/aKtOHet4Gv8ngHHeeSnZauG5q6hgnDzcUJ0tRZgrc0WsQVF7IYxstc7ABzYGZ7sa
  artifact: $(UGIS_ARCHIVE)
  draft: true
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
